# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Calendar.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ui_dlgCalendar(object):
    def setupUi(self, Ui_dlgCalendar):
        Ui_dlgCalendar.setObjectName("Ui_dlgCalendar")
        Ui_dlgCalendar.resize(352, 236)
        self.calendarWidget = QtWidgets.QCalendarWidget(Ui_dlgCalendar)
        self.calendarWidget.setGeometry(QtCore.QRect(0, 0, 351, 241))
        self.calendarWidget.setObjectName("calendarWidget")

        self.retranslateUi(Ui_dlgCalendar)
        QtCore.QMetaObject.connectSlotsByName(Ui_dlgCalendar)

    def retranslateUi(self, Ui_dlgCalendar):
        _translate = QtCore.QCoreApplication.translate
        Ui_dlgCalendar.setWindowTitle(_translate("Ui_dlgCalendar", "Dialog"))
