# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'logoempresa.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_About(object):
    def setupUi(self, About):
        About.setObjectName("About")
        About.resize(357, 222)
        About.setSizeGripEnabled(False)
        About.setModal(True)
        self.label = QtWidgets.QLabel(About)
        self.label.setGeometry(QtCore.QRect(30, 70, 71, 61))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/icono.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(About)
        self.label_2.setGeometry(QtCore.QRect(110, 50, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(About)
        self.label_3.setGeometry(QtCore.QRect(120, 100, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.btnNo = QtWidgets.QPushButton(About)
        self.btnNo.setGeometry(QtCore.QRect(110, 170, 121, 41))
        self.btnNo.setObjectName("btnNo")

        self.retranslateUi(About)
        QtCore.QMetaObject.connectSlotsByName(About)

    def retranslateUi(self, About):
        _translate = QtCore.QCoreApplication.translate
        About.setWindowTitle(_translate("About", "Dialog"))
        self.label_2.setText(_translate("About", "Version del programa: 0.0.1 "))
        self.label_3.setText(_translate("About", "Jose Maria Piña Garcia"))
        self.btnNo.setText(_translate("About", "Cerrar Venana"))
import iconoempresa_rc
