# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modificarProd.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Modificar(object):
    def setupUi(self, Modificar):
        Modificar.setObjectName("Modificar")
        Modificar.resize(400, 300)
        self.lblAviso = QtWidgets.QLabel(Modificar)
        self.lblAviso.setGeometry(QtCore.QRect(100, 150, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblAviso.setFont(font)
        self.lblAviso.setObjectName("lblAviso")
        self.label_2 = QtWidgets.QLabel(Modificar)
        self.label_2.setGeometry(QtCore.QRect(120, 40, 141, 101))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/newPrefix/kisspng-warning-sign-computer-icons-symbol-clip-art-alert-icon-image-gallery-5ab048f60c5a21.2844429515215024540506.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.btnNo = QtWidgets.QPushButton(Modificar)
        self.btnNo.setGeometry(QtCore.QRect(110, 220, 161, 31))
        self.btnNo.setObjectName("btnNo")

        self.retranslateUi(Modificar)
        QtCore.QMetaObject.connectSlotsByName(Modificar)

    def retranslateUi(self, Modificar):
        _translate = QtCore.QCoreApplication.translate
        Modificar.setWindowTitle(_translate("Modificar", "Dialog"))
        self.lblAviso.setText(_translate("Modificar", "PRODUCTO MODIFICADO"))
        self.btnNo.setText(_translate("Modificar", "vale"))
import aviso2_rc
